name: Percy Snapshots

on: 
  push:
    branches-ignore: dev/*
  pull_request:

jobs:
  call_percy_snapshots:
    uses: yext/slapshot-reusable-workflows/.github/workflows/percy_snapshots.yml@dev/percy-workflow-mapbox
    with:
      build_script: npm run build-storybook
      percy_script: npx percy storybook ./storybook-static
    secrets:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
